name = "pesde/crunchydare"
version = "0.0.0"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/crunchydare"
license = "MIT"
private = true

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[engines]
lune = "^0.9.4"
pesde = "^0.7.0-rc.1"

[dev_dependencies]
scripts = { name = "jiwonz/pesde_scripts_rojo", version = "^0.1.0-rc.1", target = "lune" }
